CWRU:
  Spectrogram:
    nfft: 1024
    fs: 48000
    nperseg: 512
    noverlap: 384
    window: 'hann'
  Split:
    signal_length: 12000
# Hust:
#   Spectrogram:
#     nfft: 1600
#     fs: 51200
#     nperseg: 580
#     noverlap: 556
#     window: 'hann'
#   Split:
#     signal_length: 12800
# Paderborn:
#   NFFT: 1600
#   Fs: 64000
#   nperseg: 580
#   noverlap: 0
#   signal_length: 640
UORED:
  Spectrogram:
    nfft: 1024
    fs: 42000
    nperseg: 512
    noverlap: 384
    window: 'hann'
  Split:
    signal_length: 10500