CWRU:
  Spectrogram:
    nfft: 2048
    fs: 42000
    nperseg: 1024
    noverlap: 896
    window: 'hann'
  Split:
    signal_length: 12000
# Hust:
#   Spectrogram:
#     nfft: 1600
#     fs: 51200
#     nperseg: 580
#     noverlap: 556
#     window: 'hann'
#   Split:
#     signal_length: 12800
# Paderborn:
#   NFFT: 1600
#   Fs: 64000
#   nperseg: 580
#   noverlap: 0
#   signal_length: 640
UORED:
  Spectrogram:
    nfft: 2048 #1024
    fs: 42000
    nperseg: 1024 #512
    noverlap: 896 #384
    window: 'hann'
  Split:
    signal_length: 10500 #2048 #10500


# # Define parameters for spectrogram computation
# # sampling frequency of 42,000
# fs = 42000
# nperseg = 505 # segments for the image
# noverlap = 460 # over lap per image used
# segment_size = 512 # setting size of image