CWRU:
  Spectrogram:
    nfft: 1600
    fs: 48000
    nperseg: 590
    noverlap: 566
    window: 'hann'
  Split:
    signal_length: 12000
# Hust:
#   NFFT: 1600
#   Fs: 51200
#   nperseg: 580
#   noverlap: 0
#   signal_length: 640
# Paderborn:
#   NFFT: 1600
#   Fs: 64000
#   nperseg: 580
#   noverlap: 0
#   signal_length: 640
# UORED:
#   NFFT: 1600
#   Fs: 42000
#   nperseg: 580
#   noverlap: 0
#   window_size: 580
#   signal_length: 640